### ISSUE TITLE
add namespace to generated kuberenetes output

### ISSUE THREAD

**Issue by marcelser** [blendle/kubecrt#24]
Hi,

I think to really make use of kubecrt in a proper way it should set the namespace by creating it first through:

```
 apiVersion: v1
    kind: Namespace
    metadata:
      name: weave
      annotations:
        cloud.weave.works/version: v1.0.0-259-g2850b85
```

and then reference it in the various other yamls by the metadata/namespace key. For automated deployment this is necessary because the yamls are automatically applied and not manually through kubectl with namespace beeing defined there.
