### ISSUE TITLE
support chart repositories behind SSL certificate authentication

### ISSUE THREAD

**Issue by JeanMertz** [blendle/kubecrt#3]
Our current API looks like this:

```yaml
apiVersion: v1
charts:
- opsgoodness/prometheus-operator:
    repo: http://charts.opsgoodness.com
```

We should also support [SSL-based authentication](https://github.com/kubernetes/helm/blob/01f8dcdc618340c1c9d9f4149dc3a72d8be62624/docs/helm/helm_repo_add.md#options), potentially with an API like this:

```yaml
apiVersion: v1
charts:
- opsgoodness/prometheus-operator:
    repo:
      url: https://charts.opsgoodness.com
      caFile: /path/to/ca
      certFile: /path/to/cert
      keyFile: /path/to/key
```

However, given that we support templating within `charts.yml`, we could also consider to _not_ point to files, but instead embed the data as base64-encoded strings, as this makes it easier to inject the values in an automated/CI-environment using environment variables:

```yaml
apiVersion: v1
charts:
- opsgoodness/prometheus-operator:
    repo:
      url: https://charts.opsgoodness.com
      ca: {{ env "MY_CA_CONTENT" | b64enc }}
      cert: {{ env "MY_CERT_CONTENT" | b64enc }}
      key: {{ env "MY_KEY_CONTENT" | b64enc }}
```

Or support both formats, if that makes sense.
