### ISSUE TITLE
add top-level "repositories" object

### ISSUE THREAD

**Issue by JeanMertz** [blendle/kubecrt#4]
Our current API looks like this:

```yaml
apiVersion: v1
charts:
- blendle/web:
    repo: https://blendle-charts.storage.googleapis.com
```

While this works, it becomes tedious if you want to add multiple charts from the same (non-stable/default) repository:

```yaml
apiVersion: v1
charts:
- blendle/web:
    repo: https://blendle-charts.storage.googleapis.com
- blendle/cron:
    repo: https://blendle-charts.storage.googleapis.com
```

The current solution to this is to launch `kubecrt` using the `--repo` flag:

```shell
kubecrt --repo="blendle=https://blendle-charts.storage.googleapis.com" charts.yml
```

After which you no longer need to define the repo in the `charts/yml`:

```yaml
apiVersion: v1
charts:
- blendle/web: {}
- blendle/cron: {}
```

This works, but if we want `charts.yml` to be a self-sustainable config, that does not depend on CLI flags, we could introduce a new `repositories` object:

```yaml
apiVersion: v1

repositories:
  blendle: https://blendle-charts.storage.googleapis.com

charts:
- blendle/web: {}
- blendle/cron: {}
```
