### ISSUE TITLE
allow list of naked charts

### ISSUE THREAD

**Issue by JeanMertz** [blendle/kubecrt#5]
Our current API looks like this:

```yaml
apiVersion: v1
charts:
- blendle/web:
    repo: https://blendle-charts.storage.googleapis.com
```

If you simply want to compile a `stable` chart, without any custom configuration, you might end up with something like this:

```yaml
apiVersion: v1
charts:
- stable/redis: {}
- stable/datadog: {}
```

Let's fix this, and also support a list of naked charts:

```yaml
apiVersion: v1
charts:
- stable/redis
- stable/datadog
```
